version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun # change if you need to
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /volume1/docker/gluetun/gluetun:/gluetun # container path
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxx # input your wireguard private key
      - WIREGUARD_PUBLIC_KEY=xxx # input your wireguard public key
      - WIREGUARD_ADDRESSES=xxx.xxx.xxx.xxx/xx # input with your wireguard address
      - WIREGUARD_MTU=1320
      - SERVER_COUNTRIES=xxx # country name
      - WIREGUARD_ALLOWED_IPS=0.0.0.0/0
      - VPN_PORT_FORWARDING=on # optional
      - BLOCK_ADS=on # optional
      - VPN_ACCELERATOR=on # optional
      - TZ=xxx # input your timezone
      - UPDATER_PERIOD=24h

  tailscale-protonvpn:
    image: tailscale/tailscale
    container_name: tailscale-protonvpn # change if you need to
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - tsvarlib:/var/lib
      - tsstate:/state
      - /dev/net/tun:/dev/net/tun
    network_mode: "service:gluetun"
    restart: always
    environment:
      - TS_HOSTNAME=xxx # named it as you wish
      - TS_AUTHKEY=tskey-auth-xxx # your authkey
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_NO_LOGS_NO_SUPPORT=true
      - TS_STATE_DIR=/state

volumes:
  tsvarlib:
    driver: local
  tsstate:
    driver: local
